# Generated by Django 3.0 on 2023-12-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("W", "Womens"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                        ],
                        default="SR",
                        max_length=2,
                    ),
                ),
                ("venue", models.CharField(max_length=100)),
                ("venue_abbr", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("season", models.CharField(blank=True, max_length=10)),
                ("grade", models.CharField(max_length=20, verbose_name="Grade")),
                ("opponent", models.CharField(max_length=20, verbose_name="Opp")),
                ("match_type", models.CharField(max_length=10, verbose_name="Type")),
                (
                    "round_number",
                    models.CharField(default="1", max_length=5, verbose_name="Rnd"),
                ),
                (
                    "points_for",
                    models.PositiveIntegerField(default=0, verbose_name="For"),
                ),
                (
                    "points_against",
                    models.PositiveIntegerField(default=0, verbose_name="Ag"),
                ),
                (
                    "bonus_points",
                    models.PositiveIntegerField(default=0, verbose_name="BP"),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Result",
                    ),
                ),
                (
                    "referee",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Ref",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="media/team_photos",
                    ),
                ),
                ("video_link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-date", "grade"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("birth_date", models.CharField(blank=True, max_length=10)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("C", "Coach"),
                            ("M", "Manager"),
                            ("P", "Physio"),
                            ("T", "Trainer"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ab_number",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=20,
                    ),
                ),
                (
                    "myrugby_id",
                    models.IntegerField(default=None, null=True, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "preferred_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("nickname", models.CharField(blank=True, default="", max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nee_name", models.CharField(blank=True, default="", max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("home_phone", models.CharField(blank=True, default="", max_length=12)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("gender", models.CharField(default="M", max_length=10)),
                ("current", models.BooleanField(default=False)),
                ("junior", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="no-image.jpg",
                        upload_to="media/player_photos",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "gender"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("W", "Womens"), ("JR", "Junior"), ("SR", "Senior")],
                        default="SR",
                        max_length=2,
                    ),
                ),
                ("year", models.CharField(max_length=20, verbose_name="Year")),
                ("grade", models.CharField(max_length=20, verbose_name="Grade")),
                (
                    "home_ground",
                    models.CharField(
                        default="Heazlett Park", max_length=40, verbose_name="Ground"
                    ),
                ),
                (
                    "competition",
                    models.CharField(default="CCRU", max_length=20, verbose_name="Opp"),
                ),
                (
                    "coach",
                    models.CharField(blank=True, max_length=40, verbose_name="Coach"),
                ),
                (
                    "manager",
                    models.CharField(blank=True, max_length=40, verbose_name="Manager"),
                ),
                (
                    "points_for",
                    models.PositiveIntegerField(default=0, verbose_name="For"),
                ),
                (
                    "points_against",
                    models.PositiveIntegerField(default=0, verbose_name="Ag"),
                ),
                (
                    "bonus_points",
                    models.PositiveIntegerField(default=0, verbose_name="BP"),
                ),
                (
                    "table_position",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Position"
                    ),
                ),
                (
                    "finals",
                    models.CharField(blank=True, max_length=40, verbose_name="Finals"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=40, verbose_name="Notes"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default="", upload_to="media/team_photos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "ordering": ["-year", "grade"],
            },
        ),
        migrations.CreateModel(
            name="PlayerYear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="players.Player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_number", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, max_length=10, null=True)),
                ("tries", models.PositiveIntegerField(default=0)),
                ("goals", models.PositiveIntegerField(default=0)),
                ("pgoals", models.PositiveIntegerField(default=0)),
                ("fgoals", models.PositiveIntegerField(default=0)),
                ("best_fairest", models.PositiveIntegerField(default=0)),
                ("cards", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "players_player",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("player_points", models.PositiveIntegerField(default=0)),
                ("player_games", models.PositiveIntegerField(default=1)),
                ("comments", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="players.Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="players.Player",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PlayerMatches",
                "ordering": ["match__date", "match__grade", "player_number"],
            },
        ),
        migrations.CreateModel(
            name="PlayerHonours",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rep_level", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("caps", models.PositiveIntegerField(blank=True, default=1, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="players.Player",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PlayerHonours",
                "ordering": ["player", "rep_level", "description"],
            },
        ),
    ]
