# Generated by Django 3.0 on 2023-12-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerhonours",
            name="comments",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="playerhonours",
            name="year",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
