# Generated by Django 3.0 on 2023-12-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_auto_20231225_2104"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerhonours",
            options={
                "ordering": ["player", "rep_level", "sub_level", "description"],
                "verbose_name_plural": "PlayerHonours",
            },
        ),
        migrations.AddField(
            model_name="playerhonours",
            name="sub_level",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
