# Generated by Django 4.2.6 on 2024-04-10 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0004_alter_match_id_alter_person_id_alter_player_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ("last_name", "first_name", "gender")},
        ),
        migrations.AlterModelOptions(
            name="playerhonours",
            options={
                "ordering": ("player", "rep_level", "sub_level", "description"),
                "verbose_name_plural": "Player Honours",
            },
        ),
        migrations.AlterModelOptions(
            name="playermatch",
            options={
                "ordering": ("match__date", "match__grade", "player_number"),
                "verbose_name_plural": "Player Matches",
            },
        ),
        migrations.AlterModelOptions(
            name="season",
            options={
                "ordering": ("-year", "grade"),
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
            },
        ),
    ]
